# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
#fos_rest:
#    body_listener:
#        enabled: false
#    param_fetcher_listener:  false
#    allowed_methods_listener:  false
 #   view:
 #       templating_formats:
  #          json: false
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
 #       rules:
 #           - { path: '^/api', priorities: [ 'json' ], fallback_format: html, prefer_extension: false }
  #          - { path: '^/', priorities: [ 'html', '*/*' ], fallback_format: ~, prefer_extension: false }